<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Custodian.Core\Custodian.Core.csproj" />
    <ProjectReference Include="..\Custodian.Platform.Windows\Custodian.Platform.Windows.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Terminal.Gui" Version="2.4.10" />
    <PackageReference Include="Velopack" Version="0.0.626" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>1.5.6.0</AssemblyVersion>
    <FileVersion>1.5.6.0</FileVersion>
    <InformationalVersion>1.5.6</InformationalVersion>
    <Product>Custodian Disk Analyzer TUI</Product>
  </PropertyGroup>

</Project>
